### ISSUE TITLE
Server crash when using "/home" command

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Presents-Direwolf20-1.16#233]
* **Modpack Version**: 1.7.0
* **Issue**: Server crash when using "/home" command
* **Link to Log or Crash File Paste**: See below
* **Is it Repeatable?**: Not consistently
* **Mod/s Affected**: Applied Energistics 2

On two different occasions, I've had my single-player game crash when using the "/home" command. In both cases, the server log reported the following:
```
[Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
        at appeng.me.cache.StatisticsCache.addChunk(StatisticsCache.java:136) ~[?:8.3.0-alpha.1]
...
        at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:255) ~[?:8.3.0-alpha.1]
        at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:524) ~[?:8.3.0-alpha.1]
        at appeng.tile.networking.CableBusTileEntity.onReady(CableBusTileEntity.java:189) ~[?:8.3.0-alpha.1]
        at appeng.hooks.TickHandler.onServerTick(TickHandler.java:234) ~[?:8.3.0-alpha.1]
        at appeng.hooks.TickHandler$$Lambda$10110/270708838.accept(Unknown Source) ~[?:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
...
        at net.minecraft.server.MinecraftServer$$Lambda$27290/383924744.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

It doesn't happen every time, though - I've used "/home" several other times without issue, and I've also jumped between dimensions without problems.

**Comment by mostlygizzards** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/6/21 5:42 PM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at appeng.me.cache.StatisticsCache.addChunk(StatisticsCache.java:136) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.cache.StatisticsCache.addNode(StatisticsCache.java:79) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:48) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.Grid.add(Grid.java:175) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.GridNode.setGrid(GridNode.java:226) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.Grid.<init>(Grid.java:68) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.GridNode.getInternalGrid(GridNode.java:138) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.GridNode.updateState(GridNode.java:195) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:135) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:128) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:255) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:524) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.tile.networking.CableBusTileEntity.onReady(CableBusTileEntity.java:189) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.hooks.TickHandler.onServerTick(TickHandler.java:234) ~[?:8.3.0-alpha.1] {re:classloading}
	at appeng.hooks.TickHandler$$Lambda$10354/19555913.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2962/800026186.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2596/1204613518.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$27766/1108511924.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by mostlygizzards** [comment]
Was also able to trigger a crash by simply flying quickly back towards my base from about 8 chunks away.

**Comment by Sunekaer** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5058

**Comment by Pingger** [comment]
Fixed in https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/747ee0dd0e7d9892b33f859d1419a6f68afe3f38
Will be available in next release

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
