### ISSUE TITLE
Game Hanging at 100% World Generation

### ISSUE THREAD

**Issue by nekosune** [FTBTeam/FTB-Presents-Direwolf20-1.16#7]
* **Modpack Version**: 1.0

* **Issue**: Game hangs at 100% world generation, will not go any further no matter what options selected

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a1718e60

* **Is it Repeatable?**: Yes

**Comment by capSAR273** [comment]
`[17Dec2020 20:28:39.567] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@60aac0d[id=43e4615d-46ab-42eb-b200-57bebfe797f7,name=nekosune,properties={textures=[com.mojang.authlib.properties.Property@694f1a0c]},legacy=false] (local:E:ffdba6a7) lost connection: Internal Exception: java.lang.ClassCastException: net.minecraft.network.login.ServerLoginNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler`

This in your log might point to the issue, but I couldn't find anything online as to why.

**Comment by dudeedud4** [comment]
I have nothing to add other than the fact that I get the same thing, but on MultiMC instead. It does NOT happen on FTB launcher for me.

**Comment by nekosune** [comment]
@dudeedud4  I get it on FTB Launcher myself

**Comment by Sunekaer** [comment]
Could i have you disable/remove MineTogether and try again? 
If that doesnt work paste the new log 
Thanks

**Comment by lamoyrl90** [comment]
Might be Waystones. I had this issue in another pack a couple days ago. Try disabling that and see if it helps.

**Comment by mcintosh109** [comment]
same here game hanged at 100% world gen
and then i seen this 
[19Dec2020 15:03:55.575] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 896146058ms or 17922921 ticks behind

**Comment by hijackster99** [comment]
I'm having this issue specifically on Mac. I have no issues on Windows. I have tried removing MineTogether and it still has the same issue with the same java cast exception. Removing Waystones. I ant to check if it will let you connect to a server and will get back when I have more info.
On another note. Is anyone havingthis problem on any other platforms?

**Comment by Pants44** [comment]
> I'm having this issue specifically on Mac. I have no issues on Windows. I have tried removing MineTogether and it still has the same issue with the same java cast exception. Removing Waystones did fix the problem. I ant to check if it will let you connect to a server and will get back when I have more info.
> On another note. Is anyone having this problem on any other platforms?
> Update: I was able to get it to connect to a server with ALL THE MODS installed. So the issue appears to only affect the server side.

Having similar issue on my mac as well. Macbook Air 2017. My main windows machine with an actual GPU does fine. Have not removed any mods to confirm potential issues.

**Comment by Sunekaer** [comment]
Can I have a spec list from you guys?
We just tested on a mac it loads just fine

**Comment by Pants44** [comment]
I know this is a low spec machine, and not intended to game on. However it runs okay when joining a server. 

https://support.apple.com/kb/SP753?locale=en_US

**Comment by Sunekaer** [comment]
> I know this is a low spec machine, and not intended to game on. However it runs okay when joining a server. My model is the lower spec CPU Intel Core i5
> 
> https://support.apple.com/kb/SP753?locale=en_US

Yeah nothing we can do about that

**Comment by nekosune** [comment]
I get the same error, with a beast of a Macbook -
Hardware Overview:

  Model Name:	MacBook Pro
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Memory:	64 GB
  Chipset Model:	AMD Radeon Pro 5600M 
  VRAM (Total):	8 GB

**Comment by nekosune** [comment]
> Could i have you disable/remove MineTogether and try again?
> If that doesnt work paste the new log
> Thanks

https://paste.feed-the-beast.com/view/5b6f1203
Without MineTogether. Crashes at the same point. 
[03Jan2021 18:56:42.139] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@48a674d4[id=43e4615d-46ab-42eb-b200-57bebfe797f7,name=nekosune,properties={textures=[com.mojang.authlib.properties.Property@6987e8ec]},legacy=false] (local:E:bd147e00) lost connection: Internal Exception: java.lang.ClassCastException: net.minecraft.network.login.ServerLoginNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler


if it helps, when loaded through MultiMC the pack works fine

**Comment by Sunekaer** [comment]
Nekosune can i get your debug from creating a new world where it doesn't work?

**Comment by nekosune** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5762237/debug.log)
Uploaded, as it was too big for paste

**Comment by LatvianModder** [comment]
Try this:

update FTB Janitor mod to this https://jenkins.latmod.com/job/FTB-Janitor/14/
in `config/ftbjanitor-common.toml` add new line `printNetworkErrors = true`
start the game, go in world, wait for it to crash/get stuck, close game, upload `latest.log` file

**Comment by nekosune** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5769143/latest.log)
Done so, and got this result.

**Comment by LatvianModder** [comment]
So there's 2 major errors:

```
packet_handler / net.minecraft.client.network.login.ClientLoginNetHandler
io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (130 > 128)
  at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:349)
  at net.minecraftforge.fml.network.FMLHandshakeMessages$S2CConfigData.decode(FMLHandshakeMessages.java:267)
  at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120)
  at java.util.Optional.map(Optional.java:215)
  at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120)
  at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
  at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
  at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
  at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
  at net.minecraftforge.fml.network.NetworkInstance.dispatchLoginPacket(NetworkInstance.java:105)
  at net.minecraftforge.fml.network.FMLLoginWrapper.lambda$wrapperReceived$5(FMLLoginWrapper.java:69)
  at java.util.Optional.ifPresent(Optional.java:159)
  at net.minecraftforge.fml.network.FMLLoginWrapper.wrapperReceived(FMLLoginWrapper.java:68)
  at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
  at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
  at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84)
  at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88)
  at java.util.Optional.map(Optional.java:215)
  at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88)
  at net.minecraft.client.network.login.ClientLoginNetHandler.func_209521_a(ClientLoginNetHandler.java:147)
  at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:34)
  at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:11)
  at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:148)
  at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
  at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304)
  at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446)
  at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
  at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404)
  at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  at java.lang.Thread.run(Thread.java:745)
```

```
packet_handler / net.minecraft.network.login.ServerLoginNetHandler
java.lang.ClassCastException: net.minecraft.network.login.ServerLoginNetHandler cannot be cast to net.minecraft.client.network.play.IClientPlayNetHandler
  at net.minecraft.network.play.server.SDisconnectPacket.func_148833_a(SourceFile:9)
  at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:148)
  at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
  at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304)
  at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446)
  at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
  at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  at java.lang.Thread.run(Thread.java:745)
  ```

Im just putting them here so its easier to read. And I suspect its 2nd more than first one, but who knows, neither of them show anything useful tbh. Hmmpf.

**Comment by LatvianModder** [comment]
Ok, now try this update https://jenkins.latmod.com/job/FTB-Janitor/15/
I renamed the logging config, so replace `printNetworkErrors = true` with `logNetworkErrors = true`
This update fixes *one* of the issues there, im not sure about the other one, but it might work

**Comment by nekosune** [comment]
That version fixed it!
