### ISSUE TITLE
Java OOM after bloodmagic exception

### ISSUE THREAD

**Issue by draav** [FTBTeam/FTB-Presents-Direwolf20-1.16#82]
* **Modpack Version**: 1.2.0

* **Issue**: I am in a Dungeon Crawl dungeon, I just recently placed a minecolonies Supply Camp down outside the dungeon. The game crashed while i was looking at my inventory. Every time I restart the game, it crashes about 30 seconds after the world loads. There is no lag on the home screen or when the game starts up.

    I have tried disabling blood magic, since i'm not using it, but it doesn't fix anything. I seem to get a botany error after that.

* **Link to Log or Crash File Paste**: console log: https://paste.feed-the-beast.com/view/cfb6f303
     error log mentioned at the end: https://paste.feed-the-beast.com/view/f1528da9

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Botania-1.16.4-410, BloodMagic-1.16.3-3.0.3-8 (i think, they are what's mentioned in the stack trace)
    
    ```
    Error while loading contents for book bloodmagic:guide 
    java.lang.RuntimeException: Error building entry bloodmagic:alchemy_array/movement_arrays
    ...
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
    ```
* **Known Fix**: don't know

---

My java configs are `-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M` as recommended in a previous issue. I am allocating 6144 MB to the instance.

**Comment by Sunekaer** [comment]
The blood magic/botania error isnt relevant in regards to this.
Its one you'll get everytime in every world.
Could be something in your inventory since that crashed you.
Try go to the world folder and rename the playerdata folder to playerdata_old that will reset your player data, try and open the world now

**Comment by draav** [comment]
tried running this again, but opening the inventory didn't crash it this time, it ran really smoothly then just killed itself again, i might just be hitting the memory limits of my computer? not sure how to tell it's weird that there's no lag at all then just crashes after 30-90 seconds

**Comment by Sunekaer** [comment]
Could you try with the newest version of the pack?

**Comment by draav** [comment]
I have loaded the game with the newest version and it seems to be working
properly.

**Comment by Sunekaer** [comment]
Thanks draav
